name: Build and Push

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        run: git -c http.sslVerify=false clone https://oauth2:${{ github.token }}@git.cname.se/${{ github.repository }}.git .

      - name: Build and push
        run: |
          echo "${{ secrets.REGISTRY_PASSWORD }}" | /usr/bin/docker login git.cname.se -u "${{ secrets.REGISTRY_USERNAME }}" --password-stdin
          /usr/bin/docker build \
            -t git.cname.se/hst/flexblankett:latest \
            -t git.cname.se/hst/flexblankett:${{ github.sha }} \
            .
          /usr/bin/docker push git.cname.se/hst/flexblankett:latest
          /usr/bin/docker push git.cname.se/hst/flexblankett:${{ github.sha }}
