name: Build and Push

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: docker
    container:
      image: docker:27
    steps:
      - name: Install dependencies
        run: apk add --no-cache nodejs git

      - name: Trust IPA CA
        run: git config --global http.sslCAInfo /etc/ssl/certs/ipa-ca.crt

      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to registry
        run: |
          echo "${{ secrets.REGISTRY_PASSWORD }}" | \
            docker login git.cname.se \
              --username "${{ secrets.REGISTRY_USERNAME }}" \
              --password-stdin

      - name: Build and push
        run: |
          docker build \
            -t git.cname.se/hst/flexblankett:latest \
            -t git.cname.se/hst/flexblankett:${{ github.sha }} \
            .

          docker push git.cname.se/hst/flexblankett:latest
          docker push git.cname.se/hst/flexblankett:${{ github.sha }}

      - name: Logout
        run: docker logout git.cname.se
